### ISSUE TITLE
Considered speed based fall dmg?

### ISSUE THREAD

**Issue by ANT83z4** [kawaiicakes/VelocityBasedDamage#1]
I was wondering if you ever plan on adding option for fall dmg to be calculated based on speed instead of blocks fallen. I have been looking for mods for 1.19.2 and this is only one at least related to speed and dmg. (for players i mean)

**Comment by kawaiicakes** [comment]
Thanks for your input! This is being considered. Unfortunately, this mod is kind of on the backburner (I kinda have been on a modding hiatus in general). We'll see in the future!
